const INR=new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0});
let expenses=JSON.parse(localStorage.getItem('expenses'))||[];
let wallet=JSON.parse(localStorage.getItem('wallet'))||[];
let historyFilter='all';
const START=new Date('2026-09-17T00:00:00');
const END=new Date('2026-10-20T23:59:59');
const TRIP_DAYS=Math.ceil((END-START)/86400000);
const qs=id=>document.getElementById(id);
const money=v=>INR.format(Number(v)||0);
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
const escapeHtml=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

function save(){localStorage.setItem('expenses',JSON.stringify(expenses));localStorage.setItem('wallet',JSON.stringify(wallet));}
function addMoney(){const a=Number(qs('moneyAmount').value);if(!a||a<=0)return alert('Enter a valid amount.');wallet.push({id:uid(),amount:a,note:qs('moneyNote').value.trim(),date:new Date().toISOString()});qs('moneyAmount').value='';qs('moneyNote').value='';save();render();showTab('home');}
function addExpense(){const a=Number(qs('amount').value);if(!a||a<=0)return alert('Enter a valid amount.');expenses.push({id:uid(),amount:a,note:qs('note').value.trim(),category:qs('expenseCategory').value||'Other',date:new Date().toISOString()});qs('amount').value='';qs('note').value='';save();render();showTab('home');}
function setHistoryFilter(filter,btn){historyFilter=filter;document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));btn?.classList.add('active');renderHistory();}
function totals(){const added=wallet.reduce((a,b)=>a+Number(b.amount||0),0);const spent=expenses.reduce((a,b)=>a+Number(b.amount||0),0);return{added,spent,remaining:added-spent};}
function tripStats(){const now=new Date();if(now<START)return{completed:0,left:TRIP_DAYS,pct:0,phase:'Preparing'};if(now>END)return{completed:TRIP_DAYS,left:0,pct:100,phase:'Completed'};const completed=Math.floor((now-START)/86400000)+1;return{completed,left:Math.max(0,TRIP_DAYS-completed),pct:Math.min(100,(completed/TRIP_DAYS)*100),phase:'In Kerala'};}
function combinedEntries(){return[...wallet.map(x=>({...x,kind:'money'})),...expenses.map(x=>({...x,kind:'expense'}))].sort((a,b)=>new Date(b.date)-new Date(a.date));}
function entryRow(x){const isMoney=x.kind==='money';return `<div class="ledger-row"><div><strong>${isMoney?'Money added':escapeHtml(x.category||'Expense')}</strong><small>${escapeHtml(x.note||'No note')} • ${new Date(x.date).toLocaleString()}</small></div><strong class="${isMoney?'positive':'negative'}">${isMoney?'+':'-'}${money(x.amount)}</strong></div>`;}

function render(){const t=totals();qs('moneyAvailable').textContent=money(t.added);qs('totalSpent').textContent=money(t.spent);qs('remainingMoney').textContent=money(t.remaining);qs('transactionCount').textContent=wallet.length+expenses.length;renderTrip();renderHomeStats();renderHistory();renderReports();}
function renderTrip(){const s=tripStats();qs('tripPhase').textContent=s.phase;qs('tripProgressBar').style.width=s.pct+'%';const now=new Date();let text='';if(now<START){const d=Math.ceil((START-now)/86400000);text=`${d} day${d===1?'':'s'} to Kerala ✈️`;}else if(now<=END){text=`Vacation Day ${s.completed} of ${TRIP_DAYS} 🌴`;}else{text='Kerala Vacation completed ❤️';}qs('tripDay').textContent=text;}
function renderHomeStats(){const s=tripStats();const t=totals();const days=Math.max(1,s.completed);const avg=s.completed?t.spent/days:0;qs('avgDailySpend').textContent=money(avg);qs('daysCompleted').textContent=s.completed;qs('daysLeft').textContent=s.left;const recent=combinedEntries().slice(0,4);qs('recentHistory').innerHTML=recent.length?recent.map(entryRow).join(''):'<div class="empty">No vacation entries yet.</div>';const badge=qs('spendStatus');if(t.remaining<0){badge.textContent='Over budget';badge.className='pill warn';}else if(t.added>0&&t.spent/t.added>0.8){badge.textContent='Watch spending';badge.className='pill caution';}else{badge.textContent='On track';badge.className='pill good';}}
function renderHistory(){let all=combinedEntries();if(historyFilter!=='all')all=all.filter(x=>x.kind===historyFilter);qs('history').innerHTML=all.length?all.map(entryRow).join(''):'<div class="empty">No matching entries.</div>';}
function renderReports(){const t=totals();const s=tripStats();const avg=s.completed?t.spent/Math.max(1,s.completed):0;const largest=expenses.reduce((m,x)=>Math.max(m,Number(x.amount||0)),0);qs('reportAvg').textContent=money(avg);qs('reportLargest').textContent=money(largest);qs('vacationReport').innerHTML=`<div class="report-grid"><div><span>Money added</span><strong>${money(t.added)}</strong></div><div><span>Spent</span><strong>${money(t.spent)}</strong></div><div><span>Remaining</span><strong>${money(t.remaining)}</strong></div><div><span>Entries</span><strong>${wallet.length+expenses.length}</strong></div></div>`;const totalsBy={};expenses.forEach(x=>{const c=x.category||'Other';totalsBy[c]=(totalsBy[c]||0)+Number(x.amount||0)});const cats=Object.entries(totalsBy).sort((a,b)=>b[1]-a[1]);qs('categoryBreakdown').innerHTML=cats.length?cats.map(([c,v])=>{const p=t.spent?Math.min(100,v/t.spent*100):0;return `<div class="break-row"><div class="status-line small"><span>${escapeHtml(c)}</span><strong>${money(v)}</strong></div><div class="progress thin"><div class="progress-bar" style="width:${p}%"></div></div></div>`}).join(''):'<div class="empty">Category insights appear after you add expenses.</div>';}
function exportData(){const data={exportedAt:new Date().toISOString(),trip:{start:'2026-09-17',end:'2026-10-20'},vacation:{wallet,expenses}};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='Abdulla-Kerala-Vacation-Tracker-Backup.json';a.click();URL.revokeObjectURL(url);}
function resetVacationData(){if(!confirm('This will erase all vacation money and expense entries from this device. Continue?'))return;if(!confirm('Final confirmation: permanently reset vacation data?'))return;wallet=[];expenses=[];save();render();alert('Vacation data reset.');}
render();